example/attpc-daq/web/attpcdaq/accounts/urls.py
from django.conf.urls import url
import django.contrib.auth.views as auth_views

urlpatterns = [
    url(r'^login/', auth_views.login, {'template_name': 'accounts/login.html'}, name='accounts/login'),
    url(r'^logout/', auth_views.logout_then_login, name='accounts/logout'),
]

example/attpc-daq/web/attpcdaq/daq/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView, TemplateView

from . import views

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='daq/status')),
    url(r'^status/$', views.status, name='daq/status'),

    url(r'^choose_experiment/$', views.ExperimentChoiceView.as_view(), name='daq/choose_experiment'),
    url(r'^new_experiment/$', views.AddExperimentView.as_view(), name='daq/new_experiment'),
    url(r'^cannot_change_experiment/$', TemplateView.as_view(template_name='daq/cannot_change_experiment.html'),
        name='daq/cannot_change_experiment'),

    url(r'^sources/$', views.ListDataSourcesView.as_view(), name='daq/data_source_list'),
    url(r'^sources/add/$', views.AddDataSourceView.as_view(), name='daq/add_source'),
    url(r'^sources/edit/(?P<pk>\d+)$', views.UpdateDataSourceView.as_view(), name='daq/update_source'),
    url(r'^sources/remove/(?P<pk>\d+)$', views.RemoveDataSourceView.as_view(), name='daq/remove_source'),
    url(r'^sources/refresh_state_all$', views.refresh_state_all, name='daq/source_refresh_state_all'),
    url(r'^sources/change_state/$', views.source_change_state, name='daq/source_change_state'),
    url(r'^sources/change_state_all/$', views.source_change_state_all, name='daq/source_change_state_all'),
    url(r'^sources/choose_config/(\d+)$', views.choose_config, name='daq/choose_config'),

    url(r'^ecc_servers/$', views.ListECCServersView.as_view(), name='daq/ecc_server_list'),
    url(r'^ecc_servers/add/$', views.AddECCServerView.as_view(), name='daq/add_ecc_server'),
    url(r'^ecc_servers/edit/(?P<pk>\d+)$', views.UpdateECCServerView.as_view(), name='daq/update_ecc_server'),
    url(r'^ecc_servers/remove/(?P<pk>\d+)$', views.RemoveECCServerView.as_view(), name='daq/remove_ecc_server'),

    url(r'^data_routers/$', views.ListDataRoutersView.as_view(), name='daq/data_router_list'),
    url(r'^data_routers/add/$', views.AddDataRouterView.as_view(), name='daq/add_data_router'),
    url(r'^data_routers/edit/(?P<pk>\d+)$', views.UpdateDataRouterView.as_view(), name='daq/update_data_router'),
    url(r'^data_routers/remove/(?P<pk>\d+)$', views.RemoveDataRouterView.as_view(), name='daq/remove_data_router'),

    url(r'^sources/download/$', views.download_datasource_list, name='daq/download_datasource_list'),
    url(r'^sources/upload/$', views.upload_datasource_list, name='daq/upload_datasource_list'),

    url(r'^runs/$', views.ListRunMetadataView.as_view(), name='daq/run_list'),
    url(r'^runs/edit/(?P<pk>\d+)$', views.UpdateRunMetadataView.as_view(), name='daq/update_run_metadata'),
    url(r'^runs/edit/latest$', views.UpdateLatestRunMetadataView.as_view(), name='daq/update_latest_run'),
    url(r'^runs/download$', views.download_run_metadata, name='daq/download_run_metadata'),

    url(r'^observables/$', views.ListObservablesView.as_view(), name='daq/observables_list'),
    url(r'^observables/add/$', views.AddObservableView.as_view(), name='daq/add_observable'),
    url(r'^observables/edit/(?P<pk>\d+)$', views.UpdateObservableView.as_view(), name='daq/update_observable'),
    url(r'^observables/remove/(?P<pk>\d+)$', views.RemoveObservableView.as_view(), name='daq/remove_observable'),
    url(r'^observables/set_ordering$', views.set_observable_ordering, name='daq/set_observable_ordering'),

    url(r'^measurements/$', views.measurement_chart, name='daq/measurement_chart'),

    url(r'^experiment_settings/$', views.experiment_settings, name='daq/experiment_settings'),

    url(r'^status/(?P<program>ecc|data_router)_log/(?P<pk>\d+)/$', views.show_log_page, name='daq/show_log'),

    url(r'^easy_setup/$', views.EasySetupPage.as_view(), name='daq/easy_setup'),
]

example/attpc-daq/web/attpcdaq/logs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.LogEntryListView.as_view(), name='logs/list'),
    url(r'^recent_panel/', views.LogEntryListFragmentView.as_view(), name='logs/recent_panel'),
    url(r'^details/(?P<pk>\d+)/', views.LogEntryDetailView.as_view(), name='logs/details'),
    url(r'^clear/', views.clear_all_logs, name='logs/clear'),
]

example/attpc-daq/web/attpcdaq/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

from .daq import urls as daq_urls
from .logs import urls as logs_urls
from .accounts import urls as account_urls


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='daq')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include(account_urls)),
    url(r'^daq/', include(daq_urls)),
    url(r'^logs/', include(logs_urls)),
]

example/attpc-daq/web/attpcdaq/daq/models.py
"""AT-TPC DAQ Models

This module defines the internal representation of the DAQ used by this control program.
Each subclass of Model is an object that will be stored in the database, and the Field
subclasses attached as attributes will be the columns in the database table.

"""

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
import xml.etree.ElementTree as ET
from zeep.client import Client as SoapClient
import os
from datetime import datetime

import logging
logger = logging.getLogger(__name__)


class ECCError(Exception):
    """Indicates that something went wrong during communication with the ECC server."""
    pass


class EccClient(object):
    def __init__(self, ecc_url):
        """A wrapper around the Zeep library's SOAP client.

        This exists to help prevent future problems if the Client class from zeep changes. That
        library is under heavy development, so it might break things in the future.

        The methods of this class are implemented by overriding `__getattr__` to pass along calls to
        the `self.service` attribute. The available methods are those defined by the SOAP protocol,
        and they are listed below.

        Methods
        -------
        GetConfigIDs()
            Get a list of the config files known to the ECC server.
        GetState()
            Fetch the current state of the ECC state machine.
        Describe(config_xml, datasource_xml)
            Perform the Describe transition.
        Prepare(config_xml, datasource_xml)
            Perform the Prepare transition.
        Configure(config_xml, datasource_xml)
            Perform the Configure transition.
        Start()
            Start acquisition.
        Stop()
            Stop acquisition.
        Breakup()
            Performs the inverse of Configure.
        Undo()
            Performs the inverse of Prepare or Describe.

        Parameters
        ----------
        ecc_url : str
            The full URL of the ECC server (i.e. "http://{address}:{port}").

        """
        wsdl_url = os.path.join(settings.BASE_DIR, 'attpcdaq', 'daq', 'ecc.wsdl')
        client = SoapClient(wsdl_url)  # Loads the service definition from ecc.wsdl
        self.service = client.create_service('{urn:ecc}ecc', ecc_url)  # This overrides the default URL from the file

        # This is a list of valid operations which is used in __getattr__ below.
        self.operations = ['GetState',
                           'Describe',
                           'Prepare',
                           'Configure',
                           'Start',
                           'Stop',
                           'Undo',
                           'Breakup',
                           'GetConfigIDs']

    def __getattr__(self, item):
        if item in self.operations:
            return getattr(self.service, item)

        else:
            raise AttributeError('EccClient has no attribute {}'.format(item))


class ConfigId(models.Model):
    """Represents a configuration file set as seen by the ECC servers.

    This will generally be retrieved from the ECC servers using a SOAP call. If this is the case, an
    object can be constructed from the XML representation using the class method ``from_xml``.

    It is important to note that this is just a representation of the config files which is used
    for communicating with the ECC server. No actual configuration is done by this program.

    ..  note::

        This model stores configuration names using the convention of the ECC server. This means
        that the actual filenames seen by the ECC server will be, for example, ``describe-[name].xcfg``.
        The prefix and file extension are added automatically by the ECC server.

    """

    #: The name of the configuration for the "describe" step
    describe = models.CharField(max_length=120)

    #: The name of the configuration for the "prepare" step
    prepare = models.CharField(max_length=120)

    #: The name of the configuration for the "configure" step
    configure = models.CharField(max_length=120)

    #: The ECC server that this configuration set is associated with
    ecc_server = models.ForeignKey('ECCServer', on_delete=models.CASCADE, null=True, blank=True)

    #: The date and time when this config was fetched from the ECC server. This is used to remove
    #: outdated configs from the database and prevent duplication.
    last_fetched = models.DateTimeField(default=datetime.now)

    class Meta:
        ordering = ('describe', 'prepare', 'configure')

    def __str__(self):
        return '{}/{}/{}'.format(self.describe, self.prepare, self.configure)

    def as_xml(self):
        """Get an XML representation of the object.

        This is useful for sending to the ECC server. The format is as follows:

        .. code-block:: xml

            <ConfigId>
                <SubConfigId type="describe">[self.describe]</SubConfigId>
                <SubConfigId type="prepare">[self.prepare]</SubConfigId>
                <SubConfigId type="configure">[self.configure]</SubConfigId>
            </ConfigId>

        Returns
        -------
        str
            The XML representation.

        """
        root = ET.Element('ConfigId')

        for tag, value in zip(('describe', 'prepare', 'configure'), (self.describe, self.prepare, self.configure)):
            node = ET.SubElement(root, 'SubConfigId', attrib={'type': tag})
            node.text = value

        return ET.tostring(root, encoding='unicode')

    @classmethod
    def from_xml(cls, node):
        """Construct a ConfigId object from the given XML representation.

        Parameters
        ----------
        node : xml.etree.ElementTree.Element or str
            The XML representation of the object, probably from the ECC server. If it's a string,
            it will be automatically converted to the appropriate XML node object.

        Returns
        -------
        new_config : ConfigId
            A ConfigId object constructed from the representation. Note that this object is **not** automatically
            committed to the database, so one should call ``new_config.save()`` if that is desired.

        """
        new_config = cls()

        if not ET.iselement(node):
            node = ET.fromstring(node)

        if node.tag != 'ConfigId':
            raise ValueError('Not a ConfigId node')
        for subnode in node.findall('SubConfigId'):
            config_type = subnode.get('type')
            if config_type == 'describe':
                new_config.describe = subnode.text
            elif config_type == 'prepare':
                new_config.prepare = subnode.text
            elif config_type == 'configure':
                new_config.configure = subnode.text
            else:
                raise ValueError('Unknown or missing config type: {:s}'.format(config_type))

        return new_config


class ECCServer(models.Model):
    """Represents an individual ECC server which may control one or more data sources.

    This object is responsible for the bulk of the program's work. It is capable of communicating with the ECC
    server process to change the state of a CoBo or MuTAnT, and it also maintains a record of the ECC server's
    current state.

    Data sources are associated with an ECC server through a many-to-one relationship, meaning that one ECC server
    may control many data sources. Alternatively, each data source may have its own ECC server, if that is desired.
    """
    #: A unique name for the ECC server
    name = models.CharField(max_length=50)

    #: The IP address of the ECC server
    ip_address = models.GenericIPAddressField(verbose_name='IP address')

    #: The TCP port that the ECC server listens on. The default value is 8083.
    port = models.PositiveIntegerField(default=8083)

    #: The experiment that this server is associated with.
    experiment = models.ForeignKey('Experiment', on_delete=models.CASCADE)

    #: The configuration file set this ECC server will use
    selected_config = models.ForeignKey(ConfigId, on_delete=models.SET_NULL, null=True, blank=True)

    #: The path to the ECC server process's log file on the computer where the process is running.
    log_path = models.CharField(max_length=500, default='~/Library/Logs/getEccSoapServer.log')

    #: The path to where the config files are stored on the remote computer.
    config_root = models.CharField(max_length=500, default='/Volumes/configs')

    #: Path where config file backups should be stored
    config_backup_root = models.CharField(max_length=500, default='~/config_backups')

    #: A constant representing the "idle" state
    IDLE = 1

    #: A constant representing the "described" state
    DESCRIBED = 2

    #: A constant representing the "prepared" state
    PREPARED = 3

    #: A constant representing the "ready" state
    READY = 4

    #: A constant representing the "running" state
    RUNNING = 5

    #: A constant that is used to tell the system to step backwards by one state
    RESET = -1

    #: A tuple of choices for the ``state`` field
    STATE_CHOICES = ((IDLE, 'Idle'),
                     (DESCRIBED, 'Described'),
                     (PREPARED, 'Prepared'),
                     (READY, 'Ready'),
                     (RUNNING, 'Running'))

    #: A dictionary mapping state constants back to state names
    STATE_DICT = dict(STATE_CHOICES)

    #: The state of the ECC server with respect to the CoBo state machine. This must be one of the choices defined by
    #: the constants attached to this class.
    state = models.IntegerField(default=IDLE, choices=STATE_CHOICES)

    #: Whether the ECC server is currently changing state
    is_transitioning = models.BooleanField(default=False)

    #: Whether the ECC server process is currently available and responding to requests
    is_online = models.BooleanField(default=False)

    class Meta:

example/attpc-daq/web/attpcdaq/logs/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseNotAllowed, HttpResponseBadRequest

from .models import LogEntry

import logging
logger = logging.getLogger(__name__)


class LogEntryListView(LoginRequiredMixin, ListView):
    model = LogEntry
    template_name = 'logs/log_entry_list.html'
    queryset = LogEntry.objects.order_by('-create_time')
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['clear_btn_redirect_target'] = reverse('logs/list')
        return context


class LogEntryListFragmentView(LoginRequiredMixin, ListView):
    model = LogEntry
    template_name = 'logs/log_list_panel_fragment.html'
    queryset = LogEntry.objects.order_by('-create_time')[:10]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['clear_btn_redirect_target'] = reverse('daq/status')
        return context


class LogEntryDetailView(LoginRequiredMixin, DetailView):
    model = LogEntry
    template_name = 'logs/log_entry_detail.html'


@login_required
def clear_all_logs(request):
    if request.method == 'POST':
        try:
            next_url = request.POST['next']
        except KeyError:
            logger.error('No "next" url provided in form')
            return HttpResponseBadRequest()

        LogEntry.objects.all().delete()
        return redirect(next_url)

    else:
        logger.error('Request method must be POST, not %s', request.method)
        return HttpResponseNotAllowed(['POST'])

example/attpc-daq/web/attpcdaq/templates/daq/cannot_change_experiment.html
{% extends 'login_base.html' %}

{% block body %}
<div class="panel panel-default" id="login-panel" style="height: 220px;">
    <div class="panel-body">
        <h4 class="">Error</h4>
        <p class="">
            The experiment cannot be changed unless all ECC servers are idle.
            Use the Reset button to return all ECC servers to the <span class="label label-idle">Idle</span>
            state and try again.
        </p>
        <div class="">
            <a class="btn btn-primary" href="{% url 'daq/status' %}">Go back</a>
        </div>
    </div>

</div>
{% endblock %}

example/attpc-daq/web/attpcdaq/templates/daq/choose_experiment.html
{% extends 'login_base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="panel panel-default" id="login-panel">
    <div class="panel-body">
        <div class="login-app-name">AT-TPC DAQ</div>
        {% crispy form %}
    </div>

</div>
{% endblock %}

example/attpc-daq/web/attpcdaq/templates/daq/data_router_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Data routers - AT-TPC DAQ{% endblock %}

{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <span>
                <span>Data routers</span>
                <div class="pull-right">
                    <a class="btn btn-primary btn-xs" href="{% url 'daq/add_data_router' %}">
                        <span class="fa fa-plus"></span> Add
                    </a>
{#                    <a class="btn btn-default btn-xs" href="{% url 'daq/upload_datasource_list' %}">#}
{#                        <span class="fa fa-upload"></span> Upload#}
{#                    </a>#}
{#                    <a class="btn btn-default btn-xs" href="{% url 'daq/download_datasource_list' %}">#}
{#                        <span class="fa fa-download"></span> Download#}
{#                    </a>#}
                </div>
            </span>
        </div>
        <table class="table table-hover">
            <tr>
                <th>Name</th>
                <th>IP address</th>
                <th>Port</th>
                <th>Connection type</th>
                <th></th>
            </tr>
            {% for router in datarouter_list %}
            <tr>
                <td>{{ router.name }}</td>
                <td>{{ router.ip_address|default:'None' }}</td>
                <td>{{ router.port|default:'None' }}</td>
                <td>{{ router.connection_type|default:'None' }}</td>
                <td class="text-right">
                    <a role="button" class="btn btn-xs btn-default"
                       href="{% url 'daq/update_data_router' router.pk %}">
                        <span class="glyphicon glyphicon-wrench"></span> Edit
                    </a>
                    <a role="button" class="btn btn-xs btn-danger"
                       href="{% url 'daq/remove_data_router' router.pk %}">
                        <span class="glyphicon glyphicon-trash"></span> Remove
                    </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

example/attpc-daq/web/attpcdaq/templates/daq/data_source_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Data Sources - AT-TPC DAQ{% endblock %}

{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <span>
                <span>Data sources</span>
                <div class="pull-right">
                    <a class="btn btn-primary btn-xs" href="{% url 'daq/add_source' %}">
                        <span class="fa fa-plus"></span> Add
                    </a>
                    <a class="btn btn-default btn-xs" href="{% url 'daq/upload_datasource_list' %}">
                        <span class="fa fa-upload"></span> Upload
                    </a>
                    <a class="btn btn-default btn-xs" href="{% url 'daq/download_datasource_list' %}">
                        <span class="fa fa-download"></span> Download
                    </a>
                </div>
            </span>
        </div>
        <table class="table table-hover">
            <tr>
                <th>Name</th>
                <th>ECC server</th>
                <th>Data router</th>
                <th></th>
            </tr>
            {% for source in datasource_list %}
            <tr>
                <td>{{ source.name }}</td>
                <td>{{ source.ecc_server|default:'None' }}</td>
                <td>{{ source.data_router|default:'None' }}</td>
                <td class="text-right">
                    <a role="button" class="btn btn-xs btn-default"
                       href="{% url 'daq/update_source' source.pk %}">
                        <span class="glyphicon glyphicon-wrench"></span> Edit
                    </a>
                    <a role="button" class="btn btn-xs btn-danger"
                       href="{% url 'daq/remove_source' source.pk %}">
                        <span class="glyphicon glyphicon-trash"></span> Remove
                    </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

example/attpc-daq/web/attpcdaq/templates/daq/ecc_server_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}ECC Servers - AT-TPC DAQ{% endblock %}

{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <span>
                <span>ECC Servers</span>
                <div class="pull-right">
                    <a class="btn btn-primary btn-xs" href="{% url 'daq/add_ecc_server' %}">
                        <span class="fa fa-plus"></span> Add
                    </a>
{#                    <a class="btn btn-default btn-xs" href="{% url 'daq/upload_datasource_list' %}">#}
{#                        <span class="fa fa-upload"></span> Upload#}
{#                    </a>#}
{#                    <a class="btn btn-default btn-xs" href="{% url 'daq/download_datasource_list' %}">#}
{#                        <span class="fa fa-download"></span> Download#}
{#                    </a>#}
                </div>
            </span>
        </div>
        <table class="table table-hover">
            <tr>
                <th>Name</th>
                <th>IP address</th>
                <th>Port</th>
                <th></th>
            </tr>
            {% for server in eccserver_list %}
            <tr>
                <td>{{ server.name }}</td>
                <td>{{ server.ip_address|default:'None' }}</td>
                <td>{{ server.port|default:'None' }}</td>
                <td class="text-right">
                    <a role="button" class="btn btn-xs btn-default"
                       href="{% url 'daq/update_ecc_server' server.pk %}">
                        <span class="glyphicon glyphicon-wrench"></span> Edit
                    </a>
                    <a role="button" class="btn btn-xs btn-danger"
                       href="{% url 'daq/remove_ecc_server' server.pk %}">
                        <span class="glyphicon glyphicon-trash"></span> Remove
                    </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

example/attpc-daq/web/attpcdaq/templates/daq/experiment_settings.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Experiment settings - AT-TPC DAQ{% endblock %}

{% block body %}
<div class="panel panel-default">
    <div class="panel-heading">
        Experiment settings
    </div>
    <div class="panel-body">
        {% crispy form %}
    </div>
</div>
{% endblock %}

example/attpc-daq/web/attpcdaq/templates/daq/generic_crispy_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ panel_title|default:'Add or edit item' }} - AT-TPC DAQ{% endblock %}

{% block body %}
<div class="panel panel-default">
    <div class="panel-heading">
        {{ panel_title|default:'Add or edit item' }}
    </div>
    <div class="panel-body">
        {% crispy form %}
    </div>
</div>
{% endblock %}

example/attpc-daq/web/attpcdaq/templates/daq/log_file.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Log file - AT-TPC DAQ{% endblock %}

{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <span>
                <span>Log file</span>
            </span>
        </div>
        <div class="panel-body">
            <pre>{{ log_content }}</pre>
        </div>
    </div>

{% endblock %}

example/attpc-daq/web/attpcdaq/templates/daq/measurement_chart.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load tags %}

{% block title %}Measurements - AT-TPC DAQ{% endblock %}

{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <span>
                <span>Measurements</span>
                <div class="pull-right">
                <a class="btn btn-default btn-xs" href="{% url 'daq/download_run_metadata' %}">
                    <span class="fa fa-download"></span> Download as CSV
                </a>
            </div>
            </span>
        </div>
        <div id="measurement-chart">
            <table class="table table-bordered">
                <tr>
                    <th>Run</th>
                    {% for observable in observables %}
                        <th>
                            {{ observable.name }}{% if observable.units %} [{{ observable.units }}]{% endif %}
                        </th>
                    {% endfor %}
                </tr>
                {% for run in runs %}
                    <tr>
                        <td>{{ run.run_number }}</td>
                        {% for observable in observables %}
                            {% with run_measurements=measurements|get_item:run.run_number %}
                                <td>{{ run_measurements|get_item:observable.name }}</td>
                            {% endwith %}
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock %}

example/attpc-daq/web/attpcdaq/templates/daq/observable_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Observables - AT-TPC DAQ{% endblock %}

{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <span>
                <span>Observables</span>
                <div class="pull-right">
                    <a class="btn btn-primary btn-xs" href="{% url 'daq/add_observable' %}">
                        <span class="fa fa-plus"></span> Add
                    </a>
                </div>
            </span>
        </div>
        <table class="table table-hover" id="observables-table">
            <thead>
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Units</th>
                    <th></th>
                </tr>
            </thead>
           <tbody>
               {% for observable in observable_list %}
                <tr data-observable-id="{{ observable.pk }}">
                    <td><span class="fa fa-bars drag-handle"></span></td>
                    <td>{{ observable.name }}</td>
                    <td>{{ observable.get_value_type_display }}</td>
                    <td>{{ observable.units|default:None }}</td>
                    <td class="text-right">
                        <a role="button" class="btn btn-xs btn-default"
                           href="{% url 'daq/update_observable' observable.pk %}">
                            <span class="fa fa-wrench"></span> Edit
                        </a>
                        <a role="button" class="btn btn-xs btn-danger"
                           href="{% url 'daq/remove_observable' observable.pk %}">
                            <span class="fa fa-trash"></span> Remove
                        </a>
                    </td>
                </tr>
                {% endfor %}
           </tbody>
        </table>
    </div>
{% endblock %}


{% block scripts %}
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>

    <script>
        $(document).ready(function () {
            // Style the object while it's being dragged.
            var dragHelper = function(e, tr) {
                var $originals = tr.children();
                var $helper = tr.clone();

                // Prevent the table row from collapsing in width
                $helper.children().each(function(index) {
                    $(this).width($originals.eq(index).width());
                });

                // Hide the buttons
                $helper.find('a').hide();

                // Make the background opaque
                $helper.addClass('dragging');

                return $helper;
            };

            var updateDatabase = function(e, ui) {
                var order = [];
                $('#observables-table').find('tr[data-observable-id]').each(function () {
                    order.push($(this).data('observable-id'));
                });

                var payload = {new_order: order};

                return $.post({
                    url: "{% url 'daq/set_observable_ordering' %}",
                    data: JSON.stringify(payload),
                    headers: {"X-CSRFToken": "{{ csrf_token }}"}
                });
            };

            $('#observables-table tbody').sortable({
                helper: dragHelper,
                stop: updateDatabase,
                axis: "y",
                opacity: 0.6,
                handle: '.drag-handle',
                cursor: 'move'
            });
        });
    </script>
{% endblock %}

example/attpc-daq/web/attpcdaq/templates/daq/remove_item.html
{% extends 'base.html' %}
{% block title %}Delete data source - AT-TPC DAQ{% endblock %}

{% block body %}
<div class="container">
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="btn btn-danger" type="submit" value="Confirm" />
</form>
</div>
{% endblock %}